### ISSUE TITLE
Modify GNUmakefile / travis configuration to run all integration tests

### ISSUE THREAD

**Issue by pierresouchay** [haproxytech/haproxy-consul-connect#34]
For now, the tests run at build time are limited to those not using dataplaneapi binary nor haproxy.

We need to test fully, so we need to modify Makefile to fetch HAProxy/dataplaneapi versions and to add it to the path to fully run tests.

@dcorbett-haproxy @aiharos How do you want to proceed?

**Comment by aiharos** [comment]
We should be able to do most of this within travis.yml. We can try making a PR

**Comment by aiharos** [comment]
Fixed with #36
