### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by pvyaka01** [haproxytech/haproxy-consul-connect#5]
Is there a working example or a link that I can check? Need an example with sidecar proxy and HAProxy-consul-connect working together. Thanks for the help!

**Comment by ShimmerGlass** [comment]
Hello, here is a full example :

## The services 

### Server
```
{
  "service": {
    "name": "server",
    "port": 8181,
    "connect": { "sidecar_service": {} }
  }
}
```

Run a test server:
```
python -m SimpleHTTPServer 8181
```

Run haproxy-connect (expects `haproxy` and `dataplaneapi` in $PATH) :
```
haproxy-consul-connect -sidecar-for server -log-level debug
```

### Client

```
{
  "service": {
    "name": "client",
    "port": 8080,
    "connect": {
      "sidecar_service": {
        "proxy": {
          "upstreams": [
            {
              "destination_name": "server",
              "local_bind_port": 9191
            }
          ]
        }
      }
    }
  }
}

```

Run haproxy-connect (expects `haproxy` and `dataplaneapi` in $PATH) :
```
haproxy-consul-connect -sidecar-for client -log-level debug
```

## Testing

```
curl -v  127.0.0.1:9191/
```

**Comment by pierresouchay** [comment]
@pvyaka01  Does it answer to your query?

**Comment by pvyaka01** [comment]
Yes, thanks. I'm still waiting for code changes to support v2 instead of v1.

**Comment by pvyaka01** [comment]
I built the new version from master and it worked. Thank you!
